package com.example.hoops_lab_v1

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import android.content.pm.PackageManager

class MainActivity: FlutterActivity() {
    // A single, consistent channel name for all native secrets
    private val NATIVE_SECRETS_CHANNEL = "com.example.hoops_lab_v1/native_secrets"

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)

        MethodChannel(flutterEngine.dartExecutor.binaryMessenger, NATIVE_SECRETS_CHANNEL).setMethodCallHandler {
            call, result ->
            when (call.method) {
                // This handles the request for the Maps key
                "getMapsApiKey" -> {
                    try {
                        val appInfo = packageManager.getApplicationInfo(packageName, PackageManager.GET_META_DATA)
                        val apiKey = appInfo.metaData.getString("com.google.android.geo.API_KEY")
                        result.success(apiKey)
                    } catch (e: Exception) {
                        result.error("UNAVAILABLE", "Could not retrieve Maps API key.", e.toString())
                    }
                }
                // This handles the request for the Gemini key
                "getGeminiApiKey" -> {
                    try {
                        // BuildConfig is generated by Gradle
                        result.success(BuildConfig.GEMINI_API_KEY)
                    } catch (e: Exception) {
                        result.error("UNAVAILABLE", "Could not retrieve Gemini API key.", e.toString())
                    }
                }
                else -> result.notImplemented()
            }
        }
    }
}